import { Injectable } from '@angular/core';
import { Product } from '../models/product';

@Injectable({
  providedIn: 'root'
})
export class ProductService {
  products: Product[] = [
    {id: 1, name: 'Green Beans', des:'Green beans, also known as string beans or snap beans, are slender, vibrant green vegetables that belong to the legume family. They are enjoyed for their crisp texture and mild, slightly sweet flavor. Whether eaten raw or cooked, green beans are a versatile ingredient in various dishes worldwide, often steamed, boiled, or stir-fried. They offer a good source of vitamins like K and C, minerals, dietary fiber, and beneficial plant compounds, making them a nutritious addition to meals.', img:'1.jpg', price: 10},
    {id: 2, name: 'Red Radish', des:'Red radishes are small, vibrant root vegetables known for their striking red skin and crisp, white flesh. With a peppery and slightly spicy flavor, they add a zesty kick to salads and dishes. Red radishes are often enjoyed raw, sliced thin to enhance their crunchy texture and add a burst of color to culinary creations. These low-calorie vegetables also offer a good amount of vitamin C, along with small amounts of other vitamins and minerals, making them a refreshing and nutritious addition to salads, sandwiches, and appetizers.', img:'2.jpg', price: 10},
    {id: 3, name: 'Tomato', des:'Tomatoes are round, juicy fruits that are commonly used as vegetables in culinary contexts. With a wide range of colors from red to yellow to green, tomatoes are known for their rich, slightly tangy flavor and versatility in various dishes. They can be enjoyed both raw and cooked, adding depth to salads, sandwiches, sauces, and more. Tomatoes are a great source of vitamins like C and K, as well as essential antioxidants like lycopene, which is associated with potential health benefits. Their culinary and nutritional diversity has secured them a central place in cuisines around the world.', img:'3.jpg', price: 10},
    {id: 4, name: 'Cauliflower', des:'Cauliflower is a versatile and nutritious cruciferous vegetable that is known for its compact, rounded head composed of tightly packed florets. While white is the most common color, it also comes in vibrant shades of green, orange, and purple. Mild in flavor, cauliflower takes on various textures and tastes depending on how it is prepared. It can be roasted, steamed, mashed, or even used as a low-carb substitute for rice or pizza crust. Rich in vitamins C and K, as well as fiber, cauliflower offers a range of health benefits and has gained popularity as a nutritious ingredient in many creative and health-conscious recipes.', img:'4.jpg', price: 10},
    {id: 5, name: 'Baby Carrot', des:"Baby carrots are small, young carrots that are typically peeled, cut, and shaped into bite-sized pieces. They are known for their convenience and sweet, mild flavor. Despite their name, most baby carrots are not actually young carrots but are instead regular-sized carrots that have been mechanically processed to create the smaller, uniform shape. Baby carrots are often enjoyed as a crunchy and nutritious snack, either on their own or with dips. They provide a good source of beta-carotene, which the body can convert into vitamin A, along with dietary fiber and other essential nutrients, making them a popular and healthy option for on-the-go snacking.", img:'5.jpg', price: 10},
    {id: 6, name: 'Onion', des:'Onions are pungent, bulbous vegetables that come in various sizes and colors, including white, yellow, and red. They are widely used as a foundational ingredient in cooking due to their distinct flavor and aroma. Onions can be enjoyed raw in salads, salsas, and sandwiches, but they truly shine when cooked. They are often sautéed, caramelized, or used as a base for soups, stews, and sauces, imparting depth and richness to dishes. Beyond their culinary value, onions offer health benefits as they contain antioxidants, vitamins, and minerals. The compounds in onions are also known to have potential anti-inflammatory and immune-boosting properties, contributing to their role as a flavorful and nutritious addition to a variety of cuisines.', img:'6.jpg', price: 10},
    {id: 7, name: 'Pumpkin', des:"Pumpkin is a vibrant and iconic autumnal vegetable, well-known for its round shape, thick orange skin, and sweet, nutty flavor. Often associated with seasonal dishes and festivities, pumpkins are used in a wide range of culinary applications. They can be roasted, pureed, or used as an ingredient in soups, pies, and baked goods. The seeds of pumpkins, known as pumpkin seeds or pepitas, are also popular for their nutritional value and can be roasted and eaten as a snack. Rich in vitamins A and C, as well as dietary fiber, pumpkins offer a healthy addition to the diet. They're not only delicious but also bring a touch of warmth and nostalgia to many fall-inspired recipes.", img:'7.jpg', price: 10},
    {id: 8, name: 'Garlic', des:"Garlic is a pungent and aromatic bulb that's widely used for its strong and distinctive flavor in cuisines around the world. Composed of individual cloves encased in a papery skin, garlic can be used both as a seasoning and a vegetable. When cooked, it becomes mellow and adds depth to dishes. It can be minced, crushed, sliced, or left whole, depending on the desired intensity of flavor. Garlic is a key ingredient in countless recipes, from savory sauces and marinades to soups and stir-fries. Beyond its culinary uses, garlic has been attributed with potential health benefits, including its natural antibiotic and immune-boosting properties. It's an essential ingredient that not only enhances the taste of food but also contributes to the overall richness of various cuisines.", img:'8.jpg', price: 10},
    {id: 10, name: 'Bell pepper', des:"Bell peppers, also known as sweet peppers or capsicums, are colorful and crisp vegetables that come in a variety of hues, including red, yellow, orange, and green. They have a mild, slightly sweet flavor that makes them a versatile ingredient in both raw and cooked dishes. Bell peppers are often enjoyed raw in salads, sliced for dips, or used as colorful garnishes. When cooked, they can be sautéed, roasted, grilled, stuffed, or added to a wide range of recipes, bringing both flavor and vibrant color to the plate. These peppers are a rich source of vitamins C and A, as well as antioxidants that contribute to their potential health benefits. With their appealing taste and visual appeal, bell peppers are a popular choice in a diverse array of cuisines.", img:'10.jpg', price: 10},
    {id: 11, name: 'Broccoli', des:"Broccoli is a nutritious and versatile cruciferous vegetable known for its dense clusters of green florets and thick stalks. It has a slightly earthy and mildly bitter flavor that becomes more mellow when cooked. Broccoli can be enjoyed in various ways, such as steamed, boiled, roasted, or stir-fried. Its tender florets and crunchy stems make it a favorite addition to salads, side dishes, and main courses. Rich in vitamins C, K, and A, as well as dietary fiber and antioxidants, broccoli offers a range of health benefits. Its potential role in supporting immune function and overall health, coupled with its culinary flexibility, has made broccoli a staple in many balanced diets and a popular choice for health-conscious eaters.", img:'11.jpg', price: 10},
    {id: 12, name: 'Cucumber', des:"Cucumber is a hydrating and refreshing vegetable with a mild, crisp texture and a subtle, cool flavor. It's composed of water-rich flesh and thin edible skin, often available in two main varieties: slicing cucumbers, which are larger and have a slightly thicker skin, and pickling cucumbers, which are smaller and ideal for making pickles. Cucumbers are commonly enjoyed in salads, sandwiches, and as a crunchy snack. Their high water content makes them especially refreshing in hot weather. Cucumbers are low in calories and a good source of vitamins and minerals, including vitamin K and potassium. Their versatility and hydrating properties contribute to their popularity as a simple, nutritious addition to a variety of dishes and beverages.", img:'12.jpg', price: 10},
    {id: 13, name: 'Daikon Radish', des:"Daikon radish, also known as white radish or winter radish, is a large, elongated root vegetable with a crisp texture and a mild, slightly peppery taste. It's commonly used in Asian cuisines, particularly in Japanese, Chinese, and Korean dishes. Daikon radish can be eaten raw, sliced into salads or used as a garnish, bringing a refreshing crunch to meals. It's also often pickled or added to soups, stews, and stir-fries, where its flavor becomes more subtle as it cooks. Daikon radish is low in calories and a good source of vitamin C, as well as dietary fiber. Its versatility and ability to add both flavor and texture to various dishes have solidified its place in many traditional and contemporary recipes.", img:'13.jpg', price: 10},
    {id: 14, name: 'Carrot', des:"Carrots are vibrant, orange root vegetables known for their sweet and earthy flavor. They're often recognized for their high beta-carotene content, which the body converts into vitamin A, contributing to healthy vision and skin. Carrots come in various sizes and can be enjoyed raw as a crunchy snack or sliced into salads. They're also a versatile cooking ingredient, used in soups, stews, roasts, and stir-fries. Beyond their rich vitamin A content, carrots also provide vitamins C and K, as well as dietary fiber. Their natural sweetness, along with their nutritional profile, makes them a popular and nutritious addition to a wide range of culinary dishes.", img:'14.jpg', price: 10},
    {id: 15, name: 'Cabbage', des:"Cabbage is a leafy and compact vegetable that comes in different varieties, such as green, red, and savoy cabbage. It's known for its slightly peppery and crisp texture, making it a versatile ingredient in both raw and cooked dishes. Cabbage can be shredded into salads, used as a crunchy topping, or added to coleslaw for a refreshing crunch. When cooked, it softens and develops a sweeter taste, and it's often used in stir-fries, soups, stews, and sautés. Cabbage is low in calories and a good source of vitamins C and K, as well as dietary fiber. It's not only a nutritious choice but also a cost-effective and hearty addition to a variety of cuisines worldwide.", img:'15.jpg', price: 10},
    {id: 16, name: 'Dragon Fruit', des:"Dragon fruit, also known as pitaya, is a unique tropical fruit that comes in several varieties with vibrant colors, including pink, yellow, and white. It's known for its distinctive appearance, featuring a spiky outer skin and sweet, juicy flesh speckled with small edible seeds. The flavor of dragon fruit is often described as mildly sweet and subtly tangy. The fruit can be enjoyed by cutting it in half and scooping out the flesh or by slicing it for various culinary applications. Dragon fruit is not only visually appealing but also a good source of vitamin C, antioxidants, and dietary fiber. With its refreshing taste and striking appearance, it's becoming increasingly popular in smoothie bowls, fruit salads, and various exotic dessert creations.", img:'16.jpg', price: 10},
    {id: 17, name: 'Grapes', des:"Grapes are small, round, and juicy fruits that grow in clusters on vines. They come in a variety of colors, including green, red, purple, and black, each with a slightly different flavor profile. Grapes are naturally sweet with a hint of tartness, making them a popular choice for snacking and as a key ingredient in various culinary creations. They can be enjoyed fresh as a refreshing treat, but they're also used to make juices, wines, jams, and dried fruits like raisins. Grapes are a good source of vitamins C and K, as well as antioxidants like resveratrol. Their versatility, portability, and nutritional benefits contribute to their popularity as a tasty and healthy addition to diets around the world.", img:'17.jpg', price: 10},
    {id: 18, name: 'Watermelon', des:"Watermelon is a juicy and refreshing summer fruit known for its high water content and sweet, thirst-quenching flavor. It's characterized by its green rind and bright red or pink flesh, although there are also yellow and orange varieties. Watermelon is often enjoyed chilled and sliced, making it a popular choice for picnics and outdoor gatherings. The flesh can also be blended into refreshing beverages like smoothies and agua frescas. Watermelon contains vitamins A and C, as well as hydration-promoting electrolytes like potassium. Its natural sweetness and hydrating properties make it a sought-after treat during hot weather, providing both a delicious taste and a way to stay cool and refreshed.", img:'18.jpg', price: 10},
    {id: 19, name: 'Papaya', des:"Papaya is a tropical fruit with a unique pear-like shape and vibrant orange flesh. It's recognized for its sweet, tropical flavor and soft, creamy texture. The flesh is punctuated with black, round seeds that are edible but often discarded. Papayas are commonly enjoyed fresh, either on their own or added to fruit salads, smoothies, and desserts. They can also be used in savory dishes, lending a touch of sweetness to salsas and salads. Papayas are rich in vitamins C and A, as well as enzymes like papain, which can aid in digestion. Their distinct taste and numerous health benefits have made them a popular and exotic addition to cuisines worldwide.", img:'19.jpg', price: 10},
    {id: 20, name: 'Green Apple', des:"Green apples are crisp and slightly tart fruits with a bright green skin. They have a refreshing and tangy flavor compared to their sweeter red and yellow counterparts. Green apples are often enjoyed fresh as a snack, but they're also used in a variety of culinary applications. They can be sliced into salads, added to savory dishes for a touch of acidity, or used to make sauces, pies, and baked goods. These apples are a good source of dietary fiber and vitamin C, and their tartness can provide a pleasant contrast in both sweet and savory dishes. With their distinct taste and versatility, green apples are a popular choice for cooking, baking, and snacking.", img:'20.jpg', price: 10},
    {id: 21, name: 'Strawberry', des:"Strawberries are vibrant red, heart-shaped fruits known for their sweet and juicy flavor. They are often associated with the arrival of spring and summer, and they're a popular choice for both snacking and incorporating into a wide range of dishes. Strawberries can be enjoyed fresh on their own, added to cereals, yogurt, and salads, or used to make jams, desserts, and smoothies. Their natural sweetness and juicy texture make them a delightful addition to various culinary creations. Strawberries are also rich in vitamin C, antioxidants, and dietary fiber, contributing to their potential health benefits. Their versatility and the burst of flavor they bring have solidified strawberries as a beloved and versatile fruit.", img:'21.jpg', price: 10},
    {id: 22, name: 'Pineapple', des:"Pineapple is a tropical fruit with a spiky, rough exterior and a juicy, sweet interior. Known for its distinctive combination of tangy and sweet flavors, pineapple is often associated with a taste of the tropics. It can be enjoyed fresh by slicing it into chunks or rings, and it's commonly used in a variety of dishes and beverages. Pineapple can be added to fruit salads, used as a topping for pizzas, incorporated into stir-fries, and blended into smoothies and cocktails. It contains vitamin C and manganese, as well as an enzyme called bromelain that may aid in digestion. With its refreshing taste and versatility, pineapple is a popular ingredient in both sweet and savory culinary creations.", img:'22.jpg', price: 10},
    {id: 23, name: 'Banana', des:"Bananas are a popular and widely consumed tropical fruit with a distinctive curved shape and yellow skin that turns darker as they ripen. They have a creamy texture and a naturally sweet flavor. Bananas are enjoyed in a variety of ways, from being eaten fresh as a convenient snack to being used as a key ingredient in baking, smoothies, and desserts. They're also a common addition to breakfast dishes like cereal, yogurt, and oatmeal. Bananas are a good source of potassium, vitamin B6, and dietary fiber. Their portability, nutritional content, and versatility have made them a staple in many diets, catering to both their taste and their contribution to a healthy lifestyle.", img:'23.jpg', price: 10},
    {id: 24, name: 'Lime', des:"Limes are small, round citrus fruits with bright green skin and a tart, tangy flavor. They are commonly used to add a burst of acidity and flavor to various dishes and beverages. Limes can be squeezed to extract their juice, which is used in marinades, dressings, cocktails, and as a flavor enhancer in a wide range of cuisines. The zest of the lime, the outermost layer of the peel, is also used for its aromatic oils in cooking and baking. Limes are a good source of vitamin C and antioxidants, offering potential health benefits. Their distinctive flavor profile, along with their ability to enhance both sweet and savory dishes, has cemented limes as an essential ingredient in culinary creations around the world.", img:'24.jpg', price: 10},
    {id: 25, name: 'Orange', des:"Oranges are round citrus fruits with a vibrant orange hue and a juicy, sweet-tangy flavor. They're one of the most popular and widely consumed fruits globally. Oranges are typically peeled to reveal segments of juicy flesh that are enjoyed fresh as a snack or added to salads, fruit cups, and desserts. They can also be juiced to make refreshing beverages and used as a flavoring agent in both sweet and savory dishes. Oranges are a rich source of vitamin C, as well as other vitamins, minerals, and dietary fiber. Their versatility, nutritional content, and natural sweetness make them a favorite ingredient for promoting both taste and health in a variety of culinary applications.", img:'25.jpg', price: 10},
    {id: 26, name: 'Blueberry', des:"Blueberries are small, round, and vibrant blue-purple berries known for their sweet and slightly tangy flavor. They are often considered a 'superfood' due to their high antioxidant content and potential health benefits. Blueberries can be enjoyed fresh as a snack or added to cereals, yogurt, and smoothies. They're also commonly used in baking, making delicious additions to muffins, pancakes, and pies. Blueberries are rich in vitamins C and K, as well as dietary fiber. Their antioxidants, such as anthocyanins, have been linked to potential benefits for brain health and cardiovascular health. With their delightful taste and impressive nutritional profile, blueberries have become a popular choice for both culinary and health-conscious purposes.", img:'26.jpg', price: 10},
    {id: 27, name: 'Cherry', des:"Cherries are small, round fruits with a smooth skin and a sweet, tart flavor. They come in various colors, including bright red, dark red, and even yellow. Cherries are typically enjoyed fresh as a snack, but they are also used in a variety of culinary creations. Sweet cherries are often used in desserts like pies, tarts, and cobblers, while sour cherries are popular for making jams, jellies, and preserves. Cherries can also be dried, candied, or used as a flavorful garnish. These fruits are a source of vitamins like C and A, as well as antioxidants like anthocyanins. The delightful combination of taste and versatility has made cherries a beloved ingredient in a wide array of dishes and treats.", img:'27.jpg', price: 10},
    {id: 28, name: 'Pomegranate', des:"Pomegranate is a unique and vibrant fruit with a tough outer rind and juicy, ruby-red arils (seed sacs) inside. It's known for its sweet and tangy flavor, as well as its reputation as a symbol of fertility and abundance in many cultures. Pomegranate arils can be enjoyed on their own as a refreshing snack or added to salads, yogurt, and desserts for a burst of flavor and color. Pomegranate juice is also popular and can be used in both beverages and culinary creations. Pomegranates are rich in antioxidants, particularly punicalagins and anthocyanins, which are believed to offer various health benefits. Their distinctive taste and potential health-promoting properties have solidified pomegranates as a sought-after fruit for both culinary and nutritional purposes.", img:'28.jpg', price: 10},
    {id: 29, name: 'Lemon', des:"Lemons are bright yellow, citrus fruits known for their sour and tangy flavor. They are prized for their versatility, as they are used for both culinary and non-culinary purposes. Lemon juice is commonly used as a flavoring agent in cooking, baking, and beverages, adding acidity and brightness to dishes. Lemon zest, the outermost layer of the peel, contains aromatic oils and is used to add fragrance to various recipes. Lemons are also a key ingredient in making lemonade and are used to garnish drinks and dishes. Rich in vitamin C and antioxidants, lemons are believed to offer various health benefits. Their sharp taste and aromatic qualities have made lemons an essential ingredient in kitchens worldwide.", img:'29.jpg', price: 10},
    {id: 30, name: 'Lemon', des:"Lemons are bright yellow, citrus fruits known for their sour and tangy flavor. They are prized for their versatility, as they are used for both culinary and non-culinary purposes. Lemon juice is commonly used as a flavoring agent in cooking, baking, and beverages, adding acidity and brightness to dishes. Lemon zest, the outermost layer of the peel, contains aromatic oils and is used to add fragrance to various recipes. Lemons are also a key ingredient in making lemonade and are used to garnish drinks and dishes. Rich in vitamin C and antioxidants, lemons are believed to offer various health benefits. Their sharp taste and aromatic qualities have made lemons an essential ingredient in kitchens worldwide.", img:'30.jpg', price: 10},
    {id: 31, name: 'Raspberry', des:"Raspberries are small, delicate berries known for their vibrant red or black color and sweet-tart flavor. They have a unique, slightly textured surface and are composed of multiple small drupelets clustered together. Raspberries can be enjoyed fresh as a snack, added to cereals, yogurt, and desserts, or used to make jams, preserves, and sauces. They are also a popular choice for baking, often featured in muffins, cakes, and pastries. Raspberries are rich in vitamins C and K, as well as dietary fiber and antioxidants like anthocyanins. Their delightful taste and nutritional benefits make them a versatile and sought-after ingredient in both sweet and savory culinary creations.", img:'31.jpg', price: 10},
    {id: 32, name: 'Green Peas', des:"Green peas are small, round, and vibrant green legumes that are commonly enjoyed as both a vegetable and a protein-rich plant food. They have a slightly sweet flavor and a tender texture. Green peas can be consumed in various ways. They can be eaten fresh from the pod, shelled and added to salads, or cooked and used as a side dish or ingredient in soups, stews, and stir-fries. Peas are a good source of vitamins like A, C, and K, as well as dietary fiber and essential minerals. Their versatility, nutritional content, and appealing taste make them a popular choice for enhancing the flavor and nutritional profile of a wide range of dishes.", img:'32.jpg', price: 10},
    {id: 33, name: 'Tomato', des:"", img:'33.jpg', price: 10},
    {id: 34, name: 'Green Gram ', des:"Green gram, also known as mung bean or moong bean, is a small, round legume that is commonly used in various cuisines around the world. It's known for its high protein content and versatility. Green gram can be consumed in different forms: sprouted, whole, split, or ground into flour. It is often used in soups, curries, stir-fries, salads, and desserts. In some cultures, it's used to make popular dishes like dals (lentil stews) and moong bean pancakes. Green gram is a good source of plant-based protein, dietary fiber, vitamins, and minerals. Its ability to adapt to different cooking methods and its nutritional value make it a staple ingredient in many vegetarian and vegan diets.", img:'34.jpg', price: 10},
    {id: 35, name: 'Blackeye Beans ', des:"Black-eyed beans, also known as black-eyed peas, are small, oval-shaped legumes with a distinctive black 'eye' or spot on one side. They are a popular ingredient in various cuisines, particularly in Southern and African American dishes. Black-eyed beans have a mild flavor and a slightly creamy texture. They can be used in a variety of recipes, such as soups, stews, salads, and casseroles. In Southern cuisine, they are often enjoyed on New Year's Day as a symbol of good luck and prosperity. Black-eyed beans are a good source of protein, dietary fiber, vitamins, and minerals. They are a versatile and nutritious ingredient that can add both taste and nutrition to a wide range of dishes.", img:'35.jpg', price: 10},
    {id: 36, name: 'Tomato', des:"", img:'36.jpg', price: 10},
    {id: 37, name: 'Anasazi Beans', des:"Anasazi beans are a type of legume that originated from the Native American Anasazi tribe in the American Southwest. These beans have a distinct appearance, featuring a mottled pattern of cream, pink, and burgundy colors. Anasazi beans have a mild, slightly nutty flavor and a creamy texture when cooked. They are often used in dishes similar to other types of beans, such as soups, stews, and salads.Anasazi beans are considered a good source of plant-based protein, dietary fiber, vitamins, and minerals. They are prized not only for their nutritional value but also for their cultural significance. These beans are known for their ability to hold their shape well during cooking, making them a versatile choice for a variety of culinary applications.", img:'37.jpg', price: 10},
    {id: 38, name: 'Chili Pepper', des:"Chili peppers, with their fiery intensity and diverse range of heat levels, are integral to global cuisine. From the mild sweetness of bell peppers to the searing spiciness of habaneros, these vibrant fruits bring depth and excitement to dishes. Used fresh, dried, or ground, they infuse salsas, sauces, and meals with their distinctive heat and flavor. Beyond their culinary impact, chili peppers contain capsaicin, offering potential health benefits and a spectrum of sensory experiences, making them an essential ingredient that adds both spice and character to a wide array of cultural and culinary creations.", img:'38.jpg', price: 10},
    {id: 39, name: 'Ginger', des:"Ginger is a knobby, aromatic root with a spicy, pungent flavor and a slightly sweet undertone. It's widely used as both a spice and a medicinal herb in various cuisines and traditional remedies. Ginger can be used fresh, dried, powdered, or even candied. It's a staple in Asian cooking, where it's added to stir-fries, curries, and soups, and it's also used to make beverages like ginger tea and ginger ale. Ginger is known for its potential digestive and anti-inflammatory benefits due to its active compound, gingerol. It adds depth and warmth to dishes while also contributing its potential health-promoting properties, making it a versatile and cherished ingredient in culinary and wellness practices.", img:'39.jpg', price: 10},
    {id: 40, name: 'Avocado', des:"Avocado is a creamy, green fruit known for its rich texture and mild, nutty flavor. It's often referred to as a 'superfood' due to its nutritional value and health benefits. Avocado is commonly used in salads, sandwiches, and spreads like guacamole. Its smooth and buttery consistency makes it a popular choice for adding creaminess to smoothies and desserts. Avocado is rich in healthy monounsaturated fats, which contribute to its creamy texture and make it a source of heart-healthy nutrients. It also contains vitamins like E, K, and C, as well as dietary fiber. With its versatility and potential health perks, avocado has become a sought-after ingredient for enhancing taste and nutritional value in various dishes.", img:'40.jpg', price: 10},
    {id: 41, name: 'Cumin', des:"Cumin is a fragrant spice derived from the seeds of the Cuminum cyminum plant. It's known for its warm and earthy flavor with a hint of citrus and a slightly nutty undertone. Cumin is a staple in many cuisines, particularly in Middle Eastern, Indian, and Mexican dishes. It's used ground or as whole seeds and is often toasted before use to enhance its aroma and taste. Cumin is a key component in spice blends like curry powder and taco seasoning, adding depth and complexity to a wide range of recipes. Beyond its culinary role, cumin has been associated with potential health benefits, such as aiding digestion and providing antioxidants. Its distinct flavor profile and versatility make it a fundamental spice that contributes depth and character to various global cuisines.", img:'41.jpg', price: 10},
  ]

  constructor() { }

  get_product_list(id_list: number[]) { 
    let products: Product[] = []
    for (let id of id_list ) { 
      const p = this.products.find((product) => product.id === id )
      
      if (p) { 
        products.push(p)
      }
    }
    return products;
  }

  get_product(id: number) { 
    let product!: Product;
    const p =  this.products.find(product => product.id == id)
    if (p) { 
      product = p;
    }
    return product
  }
}
